export interface QuizQuestion {
  id: number;
  letter: string;
  category: 'presente' | 'preterito';
  spanish: string;
  armenian: string;
  options: { key: string; text: string }[];
  correct: string;
  explanationEs?: string;
  explanationAm?: string;
}

export interface RiddleItem {
  id: number;
  spanish: string;
  armenian: string;
  answerEs: string;
  answerAm: string;
  hint?: string;
}

export interface MathItem {
  id: number;
  spanish: string;
  armenian: string;
  answerEs: string;
  answerAm: string;
  solution: string;
}

// 25 letters of the classic Spanish Rosco
export const ROSCO_LETTERS = [
  'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
  'L', 'M', 'N', 'Ñ', 'O', 'P', 'Q', 'R', 'S', 'T',
  'U', 'V', 'X', 'Y', 'Z'
];

export const PRESENTE_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    letter: 'A',
    category: 'presente',
    spanish: 'Yo ______ español todos los días.',
    armenian: 'Ես ամեն օր իսպաներեն եմ սովորում։',
    options: [
      { key: 'A', text: 'estudio' },
      { key: 'B', text: 'estudias' },
      { key: 'C', text: 'estudia' },
      { key: 'D', text: 'estudiamos' },
    ],
    correct: 'A',
    explanationEs: 'Yo estudio (verbo estudiar, 1.ª persona singular).',
    explanationAm: 'Yo (ես) դերանվան հետ օգտագործվում է estudio ձևը։',
  },
  {
    id: 2,
    letter: 'B',
    category: 'presente',
    spanish: 'Tú ______ café por la mañana.',
    armenian: 'Դու առավոտյան սուրճ ես խմում։',
    options: [
      { key: 'A', text: 'tomo' },
      { key: 'B', text: 'tomas' },
      { key: 'C', text: 'toma' },
      { key: 'D', text: 'toman' },
    ],
    correct: 'B',
    explanationEs: 'Tú tomas (verbo tomar, 2.ª persona singular).',
    explanationAm: 'Tú (դու) դերանվան հետ օգտագործվում է tomas ձևը։',
  },
  {
    id: 3,
    letter: 'C',
    category: 'presente',
    spanish: 'Carlos ______ en una oficina.',
    armenian: 'Կառլոսը աշխատում է գրասենյակում։',
    options: [
      { key: 'A', text: 'trabajo' },
      { key: 'B', text: 'trabajas' },
      { key: 'C', text: 'trabaja' },
      { key: 'D', text: 'trabajan' },
    ],
    correct: 'C',
    explanationEs: 'Carlos (él) trabaja (verbo trabajar, 3.ª persona singular).',
    explanationAm: 'Carlos (նա/él) ենթակայի համար օգտագործվում է trabaja ձևը։',
  },
  {
    id: 4,
    letter: 'D',
    category: 'presente',
    spanish: 'Nosotros ______ en Barcelona.',
    armenian: 'Մենք ապրում ենք Բարսելոնայում։',
    options: [
      { key: 'A', text: 'vivo' },
      { key: 'B', text: 'vives' },
      { key: 'C', text: 'vive' },
      { key: 'D', text: 'vivimos' },
    ],
    correct: 'D',
    explanationEs: 'Nosotros vivimos (verbo vivir, 1.ª persona plural).',
    explanationAm: 'Nosotros (մենք) դերանվան հետ օգտագործվում է vivimos ձևը։',
  },
  {
    id: 5,
    letter: 'E',
    category: 'presente',
    spanish: 'Ellos ______ al fútbol los sábados.',
    armenian: 'Նրանք շաբաթ օրերին ֆուտբոլ են խաղում։',
    options: [
      { key: 'A', text: 'juego' },
      { key: 'B', text: 'juegan' },
      { key: 'C', text: 'jugamos' },
      { key: 'D', text: 'juegas' },
    ],
    correct: 'B',
    explanationEs: 'Ellos juegan (verbo jugar con diptongación u -> ue).',
    explanationAm: 'Ellos (նրանք) դերանվան հետ օգտագործվում է juegan ձևը։',
  },
  {
    id: 6,
    letter: 'F',
    category: 'presente',
    spanish: 'Mi hermana ______ la guitarra.',
    armenian: 'Իմ քույրը կիթառ է նվագում։',
    options: [
      { key: 'A', text: 'toco' },
      { key: 'B', text: 'tocas' },
      { key: 'C', text: 'toca' },
      { key: 'D', text: 'tocamos' },
    ],
    correct: 'C',
    explanationEs: 'Mi hermana (ella) toca (verbo tocar, 3.ª persona singular).',
    explanationAm: 'Mi hermana (իմ քույրը)՝ 3-րդ դեմք եզակի (toca)։',
  },
  {
    id: 7,
    letter: 'G',
    category: 'presente',
    spanish: 'Yo ______ después del trabajo.',
    armenian: 'Ես աշխատանքից հետո հանգստանում եմ։',
    options: [
      { key: 'A', text: 'descanso' },
      { key: 'B', text: 'descansas' },
      { key: 'C', text: 'descansa' },
      { key: 'D', text: 'descansan' },
    ],
    correct: 'A',
    explanationEs: 'Yo descanso (verbo descansar, 1.ª persona singular).',
    explanationAm: 'Yo (ես) դերանվան հետ օգտագործվում է descanso ձևը։',
  },
  {
    id: 8,
    letter: 'H',
    category: 'presente',
    spanish: '¿Dónde ______ tú?',
    armenian: 'Դու որտե՞ղ ես ապրում։',
    options: [
      { key: 'A', text: 'vivo' },
      { key: 'B', text: 'vive' },
      { key: 'C', text: 'vives' },
      { key: 'D', text: 'vivimos' },
    ],
    correct: 'C',
    explanationEs: 'Tú vives (verbo vivir, 2.ª persona singular).',
    explanationAm: 'Tú (դու) դերանվան հետ օգտագործվում է vives ձևը։',
  },
  {
    id: 9,
    letter: 'I',
    category: 'presente',
    spanish: 'Pablo ______ al supermercado los lunes.',
    armenian: 'Պաբլոն երկուշաբթի օրերին գնում է սուպերմարկետ։',
    options: [
      { key: 'A', text: 'voy' },
      { key: 'B', text: 'vas' },
      { key: 'C', text: 'va' },
      { key: 'D', text: 'van' },
    ],
    correct: 'C',
    explanationEs: 'Pablo (él) va (verbo irregular ir, 3.ª persona singular).',
    explanationAm: 'Pablo (նա)՝ ir բայի 3-րդ դեմք եզակի ձևը՝ va։',
  },
  {
    id: 10,
    letter: 'J',
    category: 'presente',
    spanish: 'Nosotros ______ la cena juntos.',
    armenian: 'Մենք միասին ընթրիք ենք պատրաստում։',
    options: [
      { key: 'A', text: 'preparo' },
      { key: 'B', text: 'preparas' },
      { key: 'C', text: 'prepara' },
      { key: 'D', text: 'preparamos' },
    ],
    correct: 'D',
    explanationEs: 'Nosotros preparamos (verbo preparar, 1.ª persona plural).',
    explanationAm: 'Nosotros (մենք) դերանվան հետ օգտագործվում է preparamos ձևը։',
  },
  {
    id: 11,
    letter: 'L',
    category: 'presente',
    spanish: 'Tú ______ muchos libros.',
    armenian: 'Դու շատ գրքեր ես կարդում։',
    options: [
      { key: 'A', text: 'leo' },
      { key: 'B', text: 'lees' },
      { key: 'C', text: 'lee' },
      { key: 'D', text: 'leemos' },
    ],
    correct: 'B',
    explanationEs: 'Tú lees (verbo leer, 2.ª persona singular).',
    explanationAm: 'Tú (դու) դերանվան հետ օգտագործվում է lees ձևը։',
  },
  {
    id: 12,
    letter: 'M',
    category: 'presente',
    spanish: 'Ana ______ temprano todos los días.',
    armenian: 'Անան ամեն օր շուտ է արթնանում։',
    options: [
      { key: 'A', text: 'me levanto' },
      { key: 'B', text: 'te levantas' },
      { key: 'C', text: 'se levanta' },
      { key: 'D', text: 'nos levantamos' },
    ],
    correct: 'C',
    explanationEs: 'Ana (ella) se levanta (verbo reflexivo levantarse, 3.ª persona singular).',
    explanationAm: 'Ana (նա)՝ անդրադարձ բայի (levantarse) 3-րդ դեմք՝ se levanta։',
  },
  {
    id: 13,
    letter: 'N',
    category: 'presente',
    spanish: 'Yo ______ una película por la noche.',
    armenian: 'Ես երեկոյան ֆիլմ եմ դիտում։',
    options: [
      { key: 'A', text: 'veo' },
      { key: 'B', text: 'ves' },
      { key: 'C', text: 've' },
      { key: 'D', text: 'vemos' },
    ],
    correct: 'A',
    explanationEs: 'Yo veo (verbo ver, 1.ª persona singular).',
    explanationAm: 'Yo (ես) դերանվան հետ ver բայի ձևն է՝ veo։',
  },
  {
    id: 14,
    letter: 'Ñ',
    category: 'presente',
    spanish: 'Mis amigos ______ mucho por teléfono.',
    armenian: 'Իմ ընկերները շատ են խոսում հեռախոսով։',
    options: [
      { key: 'A', text: 'habla' },
      { key: 'B', text: 'hablamos' },
      { key: 'C', text: 'hablan' },
      { key: 'D', text: 'hablo' },
    ],
    correct: 'C',
    explanationEs: 'Mis amigos (ellos) hablan (verbo hablar, 3.ª persona plural).',
    explanationAm: 'Mis amigos (իմ ընկերները/նրանք)՝ hablan ձևը։',
  },
  {
    id: 15,
    letter: 'O',
    category: 'presente',
    spanish: 'Nosotros ______ música en casa.',
    armenian: 'Մենք տանը երաժշտություն ենք լսում։',
    options: [
      { key: 'A', text: 'escucho' },
      { key: 'B', text: 'escuchas' },
      { key: 'C', text: 'escuchamos' },
      { key: 'D', text: 'escuchan' },
    ],
    correct: 'C',
    explanationEs: 'Nosotros escuchamos (verbo escuchar, 1.ª persona plural).',
    explanationAm: 'Nosotros (մենք) դերանվան հետ օգտագործվում է escuchamos ձևը։',
  },
  {
    id: 16,
    letter: 'P',
    category: 'presente',
    spanish: '¿Qué ______ tú para desayunar?',
    armenian: 'Դու ի՞նչ ես ուտում նախաճաշին։',
    options: [
      { key: 'A', text: 'como' },
      { key: 'B', text: 'comes' },
      { key: 'C', text: 'come' },
      { key: 'D', text: 'comemos' },
    ],
    correct: 'B',
    explanationEs: 'Tú comes (verbo comer, 2.ª persona singular).',
    explanationAm: 'Tú (դու) դերանվան հետ comer բայի ձևն է՝ comes։',
  },
  {
    id: 17,
    letter: 'Q',
    category: 'presente',
    spanish: 'Mi padre ______ el coche los domingos.',
    armenian: 'Հայրս կիրակի օրերին լվանում է մեքենան։',
    options: [
      { key: 'A', text: 'lavo' },
      { key: 'B', text: 'lavas' },
      { key: 'C', text: 'lava' },
      { key: 'D', text: 'lavamos' },
    ],
    correct: 'C',
    explanationEs: 'Mi padre (él) lava (verbo lavar, 3.ª persona singular).',
    explanationAm: 'Mi padre (հայրս/նա)՝ lava ձևը։',
  },
  {
    id: 18,
    letter: 'R',
    category: 'presente',
    spanish: 'Yo ______ a mis amigos por la tarde.',
    armenian: 'Ես կեսօրից հետո հանդիպում եմ ընկերներիս։',
    options: [
      { key: 'A', text: 'encuentro' },
      { key: 'B', text: 'encuentras' },
      { key: 'C', text: 'encuentra' },
      { key: 'D', text: 'encontramos' },
    ],
    correct: 'A',
    explanationEs: 'Yo encuentro (verbo encontrar con diptongación o -> ue).',
    explanationAm: 'Yo (ես) դերանվան հետ encontrar բայի ձևն է՝ encuentro։',
  },
  {
    id: 19,
    letter: 'S',
    category: 'presente',
    spanish: 'Ellos ______ en un restaurante.',
    armenian: 'Նրանք ուտում են ռեստորանում։',
    options: [
      { key: 'A', text: 'como' },
      { key: 'B', text: 'comes' },
      { key: 'C', text: 'comen' },
      { key: 'D', text: 'comemos' },
    ],
    correct: 'C',
    explanationEs: 'Ellos comen (verbo comer, 3.ª persona plural).',
    explanationAm: 'Ellos (նրանք) դերանվան հետ comer բայի ձևն է՝ comen։',
  },
  {
    id: 20,
    letter: 'T',
    category: 'presente',
    spanish: 'Tú ______ muy bien español.',
    armenian: 'Դու շատ լավ իսպաներեն ես խոսում։',
    options: [
      { key: 'A', text: 'hablo' },
      { key: 'B', text: 'hablas' },
      { key: 'C', text: 'habla' },
      { key: 'D', text: 'hablan' },
    ],
    correct: 'B',
    explanationEs: 'Tú hablas (verbo hablar, 2.ª persona singular).',
    explanationAm: 'Tú (դու) դերանվան հետ hablar բայի ձևն է՝ hablas։',
  },
  {
    id: 21,
    letter: 'U',
    category: 'presente',
    spanish: 'Carlos ______ la puerta antes de salir.',
    armenian: 'Կառլոսը դուրս գալուց առաջ փակում է դուռը։',
    options: [
      { key: 'A', text: 'cierro' },
      { key: 'B', text: 'cierras' },
      { key: 'C', text: 'cierra' },
      { key: 'D', text: 'cerramos' },
    ],
    correct: 'C',
    explanationEs: 'Carlos (él) cierra (verbo cerrar con diptongación e -> ie).',
    explanationAm: 'Carlos (նա)՝ cerrar բայի ձևն է՝ cierra։',
  },
  {
    id: 22,
    letter: 'V',
    category: 'presente',
    spanish: 'Nosotros ______ mucha agua.',
    armenian: 'Մենք շատ ջուր ենք խմում։',
    options: [
      { key: 'A', text: 'bebo' },
      { key: 'B', text: 'bebes' },
      { key: 'C', text: 'bebe' },
      { key: 'D', text: 'bebemos' },
    ],
    correct: 'D',
    explanationEs: 'Nosotros bebemos (verbo beber, 1.ª persona plural).',
    explanationAm: 'Nosotros (մենք) դերանվան հետ beber բայի ձևն է՝ bebemos։',
  },
  {
    id: 23,
    letter: 'X',
    category: 'presente',
    spanish: '¿A qué hora ______ vosotros?',
    armenian: 'Դուք ժամը քանի՞սին եք գալիս։',
    options: [
      { key: 'A', text: 'vengo' },
      { key: 'B', text: 'vienes' },
      { key: 'C', text: 'venís' },
      { key: 'D', text: 'vienen' },
    ],
    correct: 'C',
    explanationEs: 'Vosotros venís (verbo venir, 2.ª persona plural).',
    explanationAm: 'Vosotros (դուք) դերանվան հետ venir բայի ձևն է՝ venís։',
  },
  {
    id: 24,
    letter: 'Y',
    category: 'presente',
    spanish: 'Yo ______ mi habitación cada sábado.',
    armenian: 'Ես ամեն շաբաթ մաքրում եմ իմ սենյակը։',
    options: [
      { key: 'A', text: 'limpio' },
      { key: 'B', text: 'limpias' },
      { key: 'C', text: 'limpia' },
      { key: 'D', text: 'limpian' },
    ],
    correct: 'A',
    explanationEs: 'Yo limpio (verbo limpiar, 1.ª persona singular).',
    explanationAm: 'Yo (ես) դերանվան հետ limpiar բայի ձևն է՝ limpio։',
  },
  {
    id: 25,
    letter: 'Z',
    category: 'presente',
    spanish: 'Mis padres ______ televisión por la noche.',
    armenian: 'Իմ ծնողները երեկոյան հեռուստացույց են դիտում։',
    options: [
      { key: 'A', text: 'veo' },
      { key: 'B', text: 'ves' },
      { key: 'C', text: 'ven' },
      { key: 'D', text: 'vemos' },
    ],
    correct: 'C',
    explanationEs: 'Mis padres (ellos) ven (verbo ver, 3.ª persona plural).',
    explanationAm: 'Mis padres (ծնողներս/նրանք)՝ ver բայի ձևն է՝ ven։',
  },
];

export const PRETERITO_QUESTIONS: QuizQuestion[] = [
  {
    id: 26,
    letter: '1',
    category: 'preterito',
    spanish: 'Hoy yo ______ mucho.',
    armenian: 'Այսօր ես շատ եմ աշխատել։',
    options: [
      { key: 'A', text: 'he trabajado' },
      { key: 'B', text: 'trabajé' },
      { key: 'C', text: 'trabajo' },
      { key: 'D', text: 'trabajaré' },
    ],
    correct: 'A',
    explanationEs: 'Pretérito Perfecto: con "hoy" se usa "he trabajado" (haber + participio).',
    explanationAm: 'Անցյալ կատարյալ ժամանակ (Pretérito Perfecto)՝ «hoy» (այսօր) ցուցիչով՝ he trabajado։',
  },
  {
    id: 27,
    letter: '2',
    category: 'preterito',
    spanish: 'Esta semana nosotros ______ dos películas.',
    armenian: 'Այս շաբաթ մենք երկու ֆիլմ ենք դիտել։',
    options: [
      { key: 'A', text: 'vimos' },
      { key: 'B', text: 'hemos visto' },
      { key: 'C', text: 'vemos' },
      { key: 'D', text: 'veremos' },
    ],
    correct: 'B',
    explanationEs: 'Pretérito Perfecto: con "esta semana" se usa "hemos visto" (nosotros).',
    explanationAm: '«Esta semana» (այս շաբաթ) ցուցիչով և nosotros (մենք) դերանվամբ՝ hemos visto։',
  },
  {
    id: 28,
    letter: '3',
    category: 'preterito',
    spanish: '¿______ tú alguna vez a España?',
    armenian: 'Դու երբևէ եղե՞լ ես Իսպանիայում։',
    options: [
      { key: 'A', text: 'Has ido' },
      { key: 'B', text: 'Fuiste' },
      { key: 'C', text: 'Vas' },
      { key: 'D', text: 'Irás' },
    ],
    correct: 'A',
    explanationEs: 'Experiencia de vida con "alguna vez": "has ido" (tú).',
    explanationAm: '«Alguna vez» (երբևէ) արտահայտության հետ՝ has ido (դու)։',
  },
  {
    id: 29,
    letter: '4',
    category: 'preterito',
    spanish: 'Este año ellos ______ una casa nueva.',
    armenian: 'Այս տարի նրանք նոր տուն են գնել։',
    options: [
      { key: 'A', text: 'compraron' },
      { key: 'B', text: 'han comprado' },
      { key: 'C', text: 'compran' },
      { key: 'D', text: 'comprarían' },
    ],
    correct: 'B',
    explanationEs: 'Con "este año" se usa el Pretérito Perfecto: "han comprado".',
    explanationAm: '«Este año» (այս տարի) և ellos (նրանք)՝ han comprado։',
  },
  {
    id: 30,
    letter: '5',
    category: 'preterito',
    spanish: 'Todavía no ______ la tarea.',
    armenian: 'Ես դեռ չեմ ավարտել տնային աշխատանքը։',
    options: [
      { key: 'A', text: 'he terminado' },
      { key: 'B', text: 'terminé' },
      { key: 'C', text: 'termino' },
      { key: 'D', text: 'terminaré' },
    ],
    correct: 'A',
    explanationEs: 'Con "todavía no" se utiliza "he terminado".',
    explanationAm: '«Todavía no» (դեռ ոչ) կառույցի հետ՝ he terminado։',
  },
];

export const ANIMAL_RIDDLES: RiddleItem[] = [
  {
    id: 1,
    spanish: 'Tengo cuatro patas, digo «guau» y soy buen amigo de las personas. ¿Quién soy?',
    armenian: 'Ես ունեմ չորս թաթ, ասում եմ «հաֆ-հաֆ» և մարդկանց լավ ընկերն եմ։ Ո՞վ եմ ես։',
    answerEs: 'perro',
    answerAm: 'շուն',
  },
  {
    id: 2,
    spanish: 'Soy pequeño, tengo bigotes y me gusta perseguir ratones. ¿Quién soy?',
    armenian: 'Ես փոքր եմ, բեղեր ունեմ և սիրում եմ մկների հետևից վազել։ Ո՞վ եմ ես։',
    answerEs: 'gato',
    answerAm: 'կատու',
  },
  {
    id: 3,
    spanish: 'Soy muy grande, tengo una trompa larga y orejas enormes. ¿Quién soy?',
    armenian: 'Ես շատ մեծ եմ, երկար կնճիթ և մեծ ականջներ ունեմ։ Ո՞վ եմ ես։',
    answerEs: 'elefante',
    answerAm: 'փիղ',
  },
  {
    id: 4,
    spanish: 'Vivo en la selva, tengo una gran melena y soy conocido como el rey de los animales. ¿Quién soy?',
    armenian: 'Ես ապրում եմ ջունգլիներում, մեծ բաշ ունեմ և ինձ անվանում են կենդանիների արքա։ Ո՞վ եմ ես։',
    answerEs: 'león',
    answerAm: 'առյուծ',
  },
  {
    id: 5,
    spanish: 'Tengo un cuello muy largo y puedo comer hojas de los árboles altos. ¿Quién soy?',
    armenian: 'Ես շատ երկար պարանոց ունեմ և կարող եմ բարձր ծառերի տերևներ ուտել։ Ո՞վ եմ ես։',
    answerEs: 'jirafa',
    answerAm: 'ընձուղտ',
  },
  {
    id: 6,
    spanish: 'Vivo en el agua, tengo aletas y puedo nadar muy rápido. ¿Quién soy?',
    armenian: 'Ես ապրում եմ ջրում, լողակներ ունեմ և կարող եմ շատ արագ լողալ։ Ո՞վ եմ ես։',
    answerEs: 'pez',
    answerAm: 'ձուկ',
  },
  {
    id: 7,
    spanish: 'Soy blanco y negro, vivo en lugares fríos y camino de una forma graciosa. ¿Quién soy?',
    armenian: 'Ես սև ու սպիտակ եմ, ապրում եմ ցուրտ վայրերում և զվարճալի ձևով եմ քայլում։ Ո՞վ եմ ես։',
    answerEs: 'pingüino',
    answerAm: 'պինգվին',
  },
  {
    id: 8,
    spanish: 'Tengo una casa sobre mi espalda y camino muy despacio. ¿Quién soy?',
    armenian: 'Ես իմ տունը մեջքիս վրա եմ տանում և շատ դանդաղ եմ քայլում։ Ո՞վ եմ ես։',
    answerEs: 'tortuga',
    answerAm: 'կրիա',
  },
  {
    id: 9,
    spanish: 'Tengo orejas largas, me gustan las zanahorias y salto mucho. ¿Quién soy?',
    armenian: 'Ես երկար ականջներ ունեմ, սիրում եմ գազար և շատ եմ ցատկում։ Ո՞վ եմ ես։',
    answerEs: 'conejo',
    answerAm: 'նապաստակ',
  },
  {
    id: 10,
    spanish: 'Puedo volar, tengo plumas de muchos colores y algunas veces repito palabras. ¿Quién soy?',
    armenian: 'Ես կարող եմ թռչել, տարբեր գույների փետուրներ ունեմ և երբեմն կրկնում եմ մարդկանց բառերը։ Ո՞վ եմ ես։',
    answerEs: 'loro',
    answerAm: 'թութակ',
  },
];

export const MATH_PROBLEMS: MathItem[] = [
  {
    id: 1,
    spanish: 'Pablo tiene 24 euros. Su madre le da 16 euros más. ¿Cuántos euros tiene ahora?',
    armenian: 'Պաբլոն ունի 24 եվրո։ Մայրիկը նրան տալիս է ևս 16 եվրո։ Քանի՞ եվրո ունի նա հիմա։',
    answerEs: '40 euros',
    answerAm: '40 եվրո',
    solution: '24 + 16 = 40',
  },
  {
    id: 2,
    spanish: 'Carlos compra 5 cuadernos. Cada cuaderno cuesta 4 euros. ¿Cuánto paga en total?',
    armenian: 'Կառլոսը գնում է 5 տետր։ Յուրաքանչյուր տետրն արժե 4 եվրո։ Ընդհանուր քանի՞ եվրո է վճարում։',
    answerEs: '20 euros',
    answerAm: '20 եվրո',
    solution: '5 × 4 = 20',
  },
  {
    id: 3,
    spanish: 'Lucía tiene 50 euros y compra una camiseta por 18 euros. ¿Cuánto dinero le queda?',
    armenian: 'Լուսիան ունի 50 եվրո և գնում է 18 եվրո արժողությամբ շապիկ։ Որքա՞ն գումար է մնում նրան։',
    answerEs: '32 euros',
    answerAm: '32 եվրո',
    solution: '50 - 18 = 32',
  },
  {
    id: 4,
    spanish: 'En una caja hay 36 manzanas. Se comen 9. ¿Cuántas manzanas quedan?',
    armenian: 'Տուփում կա 36 խնձոր։ Ուտում են 9-ը։ Քանի՞ խնձոր է մնում։',
    answerEs: '27 manzanas',
    answerAm: '27 խնձոր',
    solution: '36 - 9 = 27',
  },
  {
    id: 5,
    spanish: 'Hay 6 mesas y en cada mesa hay 4 personas. ¿Cuántas personas hay en total?',
    armenian: 'Կա 6 սեղան, և յուրաքանչյուր սեղանի մոտ նստած է 4 մարդ։ Ընդհանուր քանի՞ մարդ կա։',
    answerEs: '24 personas',
    answerAm: '24 մարդ',
    solution: '6 × 4 = 24',
  },
  {
    id: 6,
    spanish: 'Una entrada al cine cuesta 8 euros. Carlos compra 3 entradas. ¿Cuánto paga?',
    armenian: 'Կինոյի մեկ տոմսն արժե 8 եվրո։ Կառլոսը գնում է 3 տոմս։ Որքա՞ն է վճարում։',
    answerEs: '24 euros',
    answerAm: '24 եվրո',
    solution: '8 × 3 = 24',
  },
  {
    id: 7,
    spanish: 'Ana tiene 72 caramelos y quiere repartirlos entre 8 niños por igual. ¿Cuántos caramelos recibe cada niño?',
    armenian: 'Անան ունի 72 կոնֆետ և ուզում է դրանք հավասար բաժանել 8 երեխայի միջև։ Յուրաքանչյուր երեխա քանի՞ կոնֆետ է ստանում։',
    answerEs: '9 caramelos',
    answerAm: '9 կոնֆետ',
    solution: '72 ÷ 8 = 9',
  },
  {
    id: 8,
    spanish: 'En un autobús viajan 45 personas. En una parada bajan 13 personas. ¿Cuántas personas quedan en el autobús?',
    armenian: 'Ավտոբուսում կա 45 ուղևոր։ Կանգառում 13 մարդ իջնում է։ Քանի՞ մարդ է մնում ավտոբուսում։',
    answerEs: '32 personas',
    answerAm: '32 մարդ / ուղևոր',
    solution: '45 - 13 = 32',
  },
  {
    id: 9,
    spanish: 'Un equipo marca 3 goles en el primer partido y 5 goles en el segundo. ¿Cuántos goles marca en total?',
    armenian: 'Թիմը առաջին խաղում խփում է 3 գոլ, իսկ երկրորդում՝ 5 գոլ։ Ընդհանուր քանի՞ գոլ է խփում թիմը։',
    answerEs: '8 goles',
    answerAm: '8 գոլ',
    solution: '3 + 5 = 8',
  },
  {
    id: 10,
    spanish: 'María compra 4 botellas de agua por 2 euros cada una y un bocadillo por 5 euros. ¿Cuánto paga en total?',
    armenian: 'Մարիան գնում է 4 շիշ ջուր՝ յուրաքանչյուրը 2 եվրոյով, և մեկ սենդվիչ՝ 5 եվրոյով։ Ընդհանուր քանի՞ եվրո է վճարում։',
    answerEs: '13 euros',
    answerAm: '13 եվրո',
    solution: '(4 × 2) + 5 = 8 + 5 = 13',
  },
];
